# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='short',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
    ]
