# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 17:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_url_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 1, 17, 40, 53, 655847, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
