# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 17:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_url_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.AddField(
            model_name='url',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='url',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
