# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 20:10
from __future__ import unicode_literals

import builtins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160301_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short',
            field=models.CharField(default='4ebd2090-bedd-49c5-abfa-be05e06e7a15', max_length=255),
        ),
        migrations.AlterField(
            model_name='url',
            name='user',
            field=models.ForeignKey(default=builtins.id, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
