# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160301_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='short',
            field=models.CharField(default='f062836a-591f-4093-8178-a5ae29686eea', max_length=255),
        ),
    ]
