# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160301_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-accessed'],
            },
        ),
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='url',
            name='short',
            field=models.CharField(default='c35b84f7-906b-4035-b423-2b77299c18e8', max_length=255),
        ),
        migrations.AddField(
            model_name='click',
            name='bookmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.URL'),
        ),
    ]
