# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160302_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short',
            field=models.CharField(default='10864559-5d6b-48e5-8ae0-9ccf098a586a', max_length=255),
        ),
    ]
